name: Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout program
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project with analysis
        run: dotnet build --configuration Release --no-restore /p:RunCodeAnalysis=true
        continue-on-error: true

  test:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        configuration: [Debug, Release]
    steps:
      - name: Checkout program
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0'

      - name: Restore dependencies
        run: dotnet restore

      - name: Run tests
        run: dotnet test --configuration ${{ matrix.configuration }} --no-restore --verbosity normal
        continue-on-error: true

  code-analysis:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout program
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0'

      - name: Restore dependencies (for analysis)
        run: dotnet restore

      - name: Run code analysis via MSBuild
        run: dotnet build --configuration Release --no-restore /p:RunCodeAnalysis=true
